services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: fcg-rabbitmq

    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmquser"
      RABBITMQ_DEFAULT_PASS: "rbmq2587!@"

    ports:
      - "5672:5672"
      - "15672:15672"

    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 20


  rabbitmq-init:
    image: curlimages/curl:latest
    container_name: fcg-rabbitmq-init

    depends_on:
      rabbitmq:
        condition: service_healthy

    entrypoint:
      - /bin/sh
      - -c
      - |
        echo "Aguardando RabbitMQ Management..."

        until curl -f -u 'rabbitmquser:rbmq2587!@' \
          http://rabbitmq:15672/api/overview > /dev/null 2>&1
        do
          echo "RabbitMQ Management ainda não está pronto..."
          sleep 2
        done

        echo "RabbitMQ Management disponível."

        echo "Criando exchanges..."

        curl -f -u 'rabbitmquser:rbmq2587!@' \
          -H 'content-type: application/json' \
          -X PUT \
          http://rabbitmq:15672/api/exchanges/%2F/FCG.BuildingBlocks.Events%3AUserCreatedEvent \
          -d '{"type":"fanout","durable":true,"auto_delete":false,"internal":false,"arguments":{}}'

        curl -f -u 'rabbitmquser:rbmq2587!@' \
          -H 'content-type: application/json' \
          -X PUT \
          http://rabbitmq:15672/api/exchanges/%2F/FCG.BuildingBlocks.Events%3APaymentProcessedEvent \
          -d '{"type":"fanout","durable":true,"auto_delete":false,"internal":false,"arguments":{}}'

        echo "Criando filas..."

        curl -f -u 'rabbitmquser:rbmq2587!@' \
          -H 'content-type: application/json' \
          -X PUT \
          http://rabbitmq:15672/api/queues/%2F/notifications-user-created \
          -d '{"durable":true,"auto_delete":false,"arguments":{}}'

        curl -f -u 'rabbitmquser:rbmq2587!@' \
          -H 'content-type: application/json' \
          -X PUT \
          http://rabbitmq:15672/api/queues/%2F/notifications-payment-processed \
          -d '{"durable":true,"auto_delete":false,"arguments":{}}'

        echo "Criando bindings..."

        curl -f -u 'rabbitmquser:rbmq2587!@' \
          -H 'content-type: application/json' \
          -X POST \
          http://rabbitmq:15672/api/bindings/%2F/e/FCG.BuildingBlocks.Events%3AUserCreatedEvent/q/notifications-user-created \
          -d '{"routing_key":"","arguments":{}}'

        curl -f -u 'rabbitmquser:rbmq2587!@' \
          -H 'content-type: application/json' \
          -X POST \
          http://rabbitmq:15672/api/bindings/%2F/e/FCG.BuildingBlocks.Events%3APaymentProcessedEvent/q/notifications-payment-processed \
          -d '{"routing_key":"","arguments":{}}'

        echo "Topologia RabbitMQ criada com sucesso."