services:

  # ============================================================
  # AZURITE
  # Azure Storage local usado pelo runtime do Azure Functions
  # ============================================================
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: fcg-azurite
    restart: unless-stopped

    command: >
      azurite
      --blobHost 0.0.0.0
      --queueHost 0.0.0.0
      --tableHost 0.0.0.0

    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"


  # ============================================================
  # AZURE FUNCTIONS - NOTIFICATIONS
  # ============================================================
  notifications-functions:
    image: brnmatos/fcg-notifications-functions:1.0.0

    build:
      context: .
      dockerfile: Dockerfile

    container_name: fcg-notifications-functions
    restart: on-failure

    ports:
      - "7071:80"

    environment:
      FUNCTIONS_WORKER_RUNTIME: "dotnet-isolated"

      AzureFunctionsJobHost__Logging__Console__IsEnabled: "true"

      # Azure Storage local via Azurite
      AzureWebJobsStorage: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;QueueEndpoint=http://azurite:10001/devstoreaccount1;TableEndpoint=http://azurite:10002/devstoreaccount1;"

    depends_on:
      azurite:
        condition: service_started
