services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: fcg-rabbitmq

    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmquser"
      RABBITMQ_DEFAULT_PASS: "rbmq2587!@"

    ports:
      - "5672:5672"
      - "15672:15672"