apiVersion: apps/v1
kind: Deployment
metadata:
  name: fcg-notifications-functions
  namespace: fcg
  labels:
    app: fcg-notifications-functions
spec:
  replicas: 1

  selector:
    matchLabels:
      app: fcg-notifications-functions

  template:
    metadata:
      labels:
        app: fcg-notifications-functions

    spec:
      containers:
        - name: fcg-notifications-functions
          image: brnmatos/fcg-notifications-functions:1.0.0
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 80
              protocol: TCP

          envFrom:
            - configMapRef:
                name: fcg-notifications-config

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: fcg-notifications-functions
  namespace: fcg
spec:
  selector:
    app: fcg-notifications-functions
  ports:
    - name: http
      port: 80
      targetPort: http
